sudo: false
notifications:
  email: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
env:
  - JAX_ENABLE_X64=0 JAX_NUM_GENERATED_CASES=100
  - JAX_ENABLE_X64=1 JAX_NUM_GENERATED_CASES=100
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels conda-forge
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip six protobuf>=3.6.0 absl-py opt_einsum numpy scipy pytest-xdist
  - pip install jaxlib
  - pip install -v .
script:
  - pytest -n 2 tests examples
